# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "email"
name = "Email"
url = "mailto:kxming0229@gmail.com"

[social.params]
icon = "email"

[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://www.facebook.com/p/King-Shawn-100092679065959/"

[social.params]
icon = "facebook"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/ShawnKxming"

[social.params]
icon = "x"

[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/shawnkxming"

[social.params]
icon = "telegram"

[[social]]
identifier = "medium"
name = "Medium"
url = "https://medium.com/@kxming"

[social.params]
icon = "medium"

